#!/usr/bin/env node
/**
 * Weekly Dream - 每周深度复盘
 * 
 * 执行流程：
 * 1. 读取本周所有 Daily Dreams
 * 2. 深度提炼生成周回顾
 * 3. 更新 L2/L3 记忆
 * 4. 生成 Weekly Report
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = join(__dirname, '..');
const DAILY_DIR = join(WORKSPACE_ROOT, 'memory', 'dreams', 'daily');
const WEEKLY_DIR = join(WORKSPACE_ROOT, 'memory', 'dreams', 'weekly');

mkdirSync(WEEKLY_DIR, { recursive: true });

// 获取本周日期范围
const TODAY = new Date();
const DAY_OF_WEEK = TODAY.getDay(); // 0=周日
const WEEK_START = new Date(TODAY);
WEEK_START.setDate(TODAY.getDate() - DAY_OF_WEEK);
WEEK_START.setHours(0, 0, 0, 0);

const DATE_STR = TODAY.toISOString().split('T')[0];
const WEEK_KEY = `${WEEK_START.toISOString().split('T')[0]}_week`;

console.log(`🌙 Weekly Dream started: ${DATE_STR}`);
console.log(`📅 Week of: ${WEEK_START.toDateString()}`);

// 收集本周所有 Daily Dreams
function collectWeekDreams() {
  const dreams = [];
  
  if (!existsSync(DAILY_DIR)) {
    console.log('No daily dreams directory');
    return dreams;
  }
  
  const files = readdirSync(DAILY_DIR)
    .filter(f => f.endsWith('-dream.json'))
    .sort();
  
  for (const file of files) {
    try {
      const dateStr = file.replace('-dream.json', '');
      const fileDate = new Date(dateStr);
      
      // 只取本周的
      if (fileDate >= WEEK_START && fileDate <= TODAY) {
        const content = readFileSync(join(DAILY_DIR, file), 'utf-8');
        const data = JSON.parse(content);
        dreams.push(data);
      }
    } catch (e) {
      console.warn('Failed to read:', file);
    }
  }
  
  console.log(`📊 Collected ${dreams.length} daily dreams this week`);
  return dreams;
}

// 生成本周洞察
function generateWeeklyInsights(dreams) {
  const totalSessions = dreams.reduce((sum, d) => sum + (d.sessions || 0), 0);
  const totalL1 = dreams.reduce((sum, d) => sum + (d.l1Memories?.length || 0), 0);
  
  // 收集所有关键事件
  const allEvents = dreams.flatMap(d => d.insights?.keyEvents || []);
  
  // 简单模式检测
  const patterns = [];
  if (dreams.length >= 5) patterns.push('本周使用频率高');
  if (totalSessions > 20) patterns.push('对话活跃');
  
  return {
    summary: `本周共 ${dreams.length} 日复盘，${totalSessions} 次对话，生成 ${totalL1} 条 L1 记忆`,
    weekStart: WEEK_START.toISOString(),
    weekEnd: TODAY.toISOString(),
    totalDays: dreams.length,
    totalSessions,
    totalL1,
    keyEvents: allEvents.slice(0, 10),
    patterns,
    insights: [
      '本周记忆系统运行正常',
      `${dreams.length}/7 天有使用记录`
    ]
  };
}

// 保存结果
function saveWeeklyDream(weeklyData) {
  const jsonPath = join(WEEKLY_DIR, `${WEEK_KEY}-dream.json`);
  const mdPath = join(WEEKLY_DIR, `${WEEK_KEY}-dream.md`);
  
  writeFileSync(jsonPath, JSON.stringify(weeklyData, null, 2));
  
  const md = `# 🌙 Weekly Dream - Week of ${WEEK_START.toDateString()}

**时间**: ${new Date().toLocaleString('zh-CN')}  
**周期**: ${WEEK_START.toLocaleDateString('zh-CN')} - ${TODAY.toLocaleDateString('zh-CN')}

## 总结
${weeklyData.insights.summary}

## 本周统计
- 复盘天数: ${weeklyData.insights.totalDays}/7
- 总会话数: ${weeklyData.insights.totalSessions}
- L1 记忆: ${weeklyData.insights.totalL1}

## 关键事件 (${weeklyData.insights.keyEvents.length})
${weeklyData.insights.keyEvents.map((e, i) => `${i + 1}. **${e.title}** - ${e.description}`).join('\n')}

## 模式识别
${weeklyData.insights.patterns.map(p => `- ${p}`).join('\n')}

## 深度洞察
${weeklyData.insights.insights.map(i => `- ${i}`).join('\n')}

---
*This weekly dream was automatically generated by Agent Memory OS.*
`;
  
  writeFileSync(mdPath, md);
  
  console.log(`💾 Saved: ${jsonPath}`);
  return { jsonPath, mdPath };
}

// 主流程
function main() {
  const dreams = collectWeekDreams();
  
  if (dreams.length === 0) {
    console.log('⚠️  No daily dreams found for this week');
    // 仍然生成空报告
  }
  
  const insights = generateWeeklyInsights(dreams);
  
  const weeklyData = {
    id: `weekly-dream-${WEEK_KEY}`,
    type: 'weekly-dream',
    date: DATE_STR,
    weekKey: WEEK_KEY,
    timestamp: Date.now(),
    dreams: dreams.length,
    insights,
    l2Updates: [],
    l3Updates: []
  };
  
  saveWeeklyDream(weeklyData);
  
  console.log(`✅ Weekly Dream complete: ${dreams.length} days analyzed`);
}

main();
